spring.application.name=urlshortner

# Import the .env file from the project root
spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Brevo Mail Configuration
brevo.api.url=https://api.brevo.com/v3/smtp/email
brevo.api.key=${BREVO_API_KEY}
brevo.sender.name=noreply
brevo.sender.email=hostelease123@gmail.com

# JWT Security Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION:86400000}

# Short URL Configuration
app.short-url-base=http://localhost:8080

# Redis Configuration
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}


